root = "G:\\My Drive\\PROJECT_VIS_PARADIM\\"
analysis_result = "G:\\My Drive\\PROJECT_VIS_PARADIM\\analyze_result\\"
bulk_data = "G:\\My Drive\\PROJECT_VIS_PARADIM\\DATA_bulk\\"
final_result_dir = "G:\\My Drive\\PROJECT_VIS_PARADIM\\final_result\\"
processed_script = "G:\\My Drive\\PROJECT_VIS_PARADIM\\processed_script\\"
script = "G:\\My Drive\\PROJECT_VIS_PARADIM\\script\\"
